[project]
name = "homework-deploy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.120.4",
    "scikit-learn==1.6.1",
    "uvicorn>=0.38.0",
]
